version: "2"
services:
  pcmt-integration:
    image: openlmis/pcmt-integration
    links:
      - db
      - log
    ports:
      - "8080"
    env_file: .env
  db:
    image: openlmis/postgres:9.6
    env_file: .env
  log:
    image: openlmis/rsyslog:1
    volumes:
      - '../logs/pcmt-integration:/var/log'
